/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-07 04:52:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"home.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 try
{
	response.setHeader("Cache-Control","no-cache, no-store, must-revalidate");
	response.setHeader("Pragma","no-cache");	


if(session.getAttribute("key2")== null)
{
	response.sendRedirect("adminlogin.html");
}
}
catch(Exception e)
{
	
}

      out.write("\r\n");
      out.write("<div class=\"topbar\">\r\n");
      out.write("\t\t<img src=\"images/bloodicon.jpg\" height=\"120px\" width=\"120px\" id=\"logo-image\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<span>Blood Bank Of India</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<ul>\r\n");
      out.write("  <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("  <li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("  <li><a href=\"aboutus.html\">About Us</a></li>\r\n");
      out.write("  <li><a href=\"faq.html\">FAQ's</a></li>\r\n");
      out.write("  \r\n");
      out.write("  <li style=\"float: right;\"><a href=\"logout.jsp\">Log Out</a></li>\r\n");
      out.write("  <li style=\"float: right;\"><a href=\"memberlogin.html\">Member Login</a></li> \r\n");
      out.write("</ul>\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("<a href=\"campupdate.jsp\"><button class=\"button-2 button1\">Update Blood Camps</button></a>\r\n");
      out.write("<a href=\"bankupdate.jsp\"><button class=\"button-2 button2\" style=\"text-shadow: 2px 2px 5px red;\">Update Blood Banks</button></a>\r\n");
      out.write("<div class=\"news\">\r\n");
      out.write("  <img class=\"mySlides\" src=\"images/news1.jpg\" width=\"525px\" height=\"605px\">\r\n");
      out.write("  <img class=\"mySlides\" src=\"images/news2.jpg\" width=\"525px\" height=\"605px\">\r\n");
      out.write("  <img class=\"mySlides\" src=\"images/news3.jpg\" width=\"525px\" height=\"605px\">\r\n");
      out.write("</div>\r\n");
      out.write("<a href=\"#\"><button class=\"button-2 button3\" style=\"text-shadow: 2px 2px 5px red;\">Update Blood Banks Availability</button></a>\r\n");
      out.write("<a href=\"profileupdate.jsp\"><button class=\"button-2 button4\" style=\"text-shadow: 2px 2px 5px red;\">Update Profile</button></a>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("var myIndex = 0;\r\n");
      out.write("carousel();\r\n");
      out.write("\r\n");
      out.write("function carousel() {\r\n");
      out.write("  var i;\r\n");
      out.write("  var x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("  for (i = 0; i < x.length; i++) {\r\n");
      out.write("    x[i].style.display = \"none\";  \r\n");
      out.write("  }\r\n");
      out.write("  myIndex++;\r\n");
      out.write("  if (myIndex > x.length) {myIndex = 1}    \r\n");
      out.write("  x[myIndex-1].style.display = \"block\";  \r\n");
      out.write("  setTimeout(carousel, 2000); // Change image every 2 seconds\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"th-bar\">\r\n");
      out.write("  <img src=\"images/news4.jpg\" height=\"300px\" width=\"30%\">\r\n");
      out.write("  <div class=\"th-bar-par\"><h1>Why donate blood?</h1><p>Our nation requires 4 crore units of blood while only 40 lakh units are available.Every two seconds someone needs blood.There is no substitute for human blood. It cannot be manufactured.Blood donation is extremely noble deed, yet there is scarcity of regular blood donors across india.We focus on creating and expanding a virtual army of blood donating volunteers who can be searched or contacted by family of patients in time of need.</p></div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
